/* SELECAO, PROJECAO E JUNCAO */


/* PROJECAO : TUDO QUE VOCÊ QUER VER NA TELA - COMANDO SELECT */

SELECT NOW() AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW()
FROM CLIENTE;


/* SELEÇÃO : É UM SUBCONJUNTO DOS REGISTROS DE UMA TABELA */

SELECT NOME, SEXO, EMAIL
FROM CLIENTE
WHERE SEXO = 'F';

SELECT NUMERO
FROM TELEFONE
WHERE TIPO = 'CEL';

/* JUNÇÃO : COMANDO JOIN */

SELECT NOME, EMAIL, ID
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

-- NOME, SEXO, BAIRRO, CIDADE

-- Essa query funciona, mas NÃO é recomendada!!
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE ID = ID_CLIENTE;

-- Se quisermos selecionar dentro deste resultado, precisa de lógica adicional
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE ID = ID_CLIENTE
AND SEXO = 'F';

-- Junção adequada : JOIN
SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON ID = ID_CLIENTE;

-- Com filtro:
SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE /* ORIGEM */
    INNER JOIN ENDERECO /* JUNCAO */
    ON ID = ID_CLIENTE
WHERE SEXO = 'F'; /* SELECAO */

-- NOME, SEXO, EMAIL, TIPO, NUMERO
SELECT NOME, SEXO, EMAIL, TIPO, NUMERO
FROM CLIENTE
    INNER JOIN TELEFONE
    ON ID = ID_CLIENTE;

-- NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO
-- Sintaxe de "ponteiramento": auxilia na performance do DB
SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO
FROM CLIENTE C
    INNER JOIN ENDERECO E
    ON C.ID = E.ID_CLIENTE
    INNER JOIN TELEFONE T
    ON C.ID = T.ID_CLIENTE;
