/*
    DML - DATA MANIPULATION LANGUAGE
    DDL - DATA DEFINITION LANGUAGE
    DCL - DATA CONTROL LANGUAGE
    TCL - TRANSACTION CONTROL LANGUAGE
*/

-- DML

/*
INSERT
FILTROS (WHERE)
UPDATE
DELETE
*/

-- DDL

/*
 CREATE
 ALTER TABLE
 CHANGE
 ADD
*/

CREATE TABLE PRODUTO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR(30) NOT NULL,
    PRECO INT,
    FRETE FLOAT(10, 2) NOT NULL
);

-- CHANGE altera tudo de uma coluna
ALTER TABLE PRODUTO
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;
CHANGE VALOR_UNITARIO VALOR_UNITARIO INT;

-- MODIFY não altera o nome
ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR(50) NOT NULL;

-- ADD : adicionando colunas
ALTER TABLE PRODUTO
ADD PESO FLOAT(10, 2) NOT NULL;
